#!/bin/sh /etc/rc.common

START=99
STOP=99

# TODO: Put in correct code location
CODE_LOC=/root
PID_FILE=/var/run/kombucha_monitor.pid

start() {
    # TODO: don't start if PID already exists
    # TODO: Do I need to background the process?
    ($CODE_LOC/onion_omega/nodejs/kombucha_monitor/kombucha.js)&
    echo $! > $PID_FILE
}

stop() {
    # TODO: don't try to stop if PID does not exist
    kill $(cat $PID_FILE)
}
