#!/bin/sh /etc/rc.common

START=99
STOP=99

CODE_LOC=/root/onion_omega/nodejs/kombucha_monitor
PID_FILE=/var/run/kombucha_monitor.pid

start() {
    # TODO: don't start if PID already exists
    # TODO: Do I need to background the process?
    ($CODE_LOC/kombucha.js > /var/log/kombucha_monitor.log)&
    echo $! > $PID_FILE
}

stop() {
    # TODO: don't try to stop if PID does not exist
    kill $(cat $PID_FILE)
}
