usage:
	@echo "Usage:"
	@echo "* sync: RSync code to Onion Omega Dash"
	@echo "* shell: SSH into Dash"

sync:
	rsync -a -v ./ root@192.168.1.201:/root/src/onion_omega/python/ws-panel

shell:
	ssh root@192.168.1.201
